In [1]:
import pandas as pd

In [4]:
user_df = pd.read_csv('data/첨부파일 01_User_Profile.csv', encoding='utf-8')
event_log_df = pd.read_csv('data/첨부파일 02_Event_Log.csv', encoding='utf-8')

display(user_df)
display(event_log_df)

        User_ID        가입일자    가입경로       기기 알림수신동의여부 알림수신동의_변경일자
0      U0000001  2025-01-25     오가닉      iOS     True         NaN
1      U0000002  2025-05-06     오가닉      iOS    False  2025-05-24
2      U0000003  2025-05-14     오가닉      iOS    False         NaN
3      U0000004  2025-02-23  퍼포먼스광고  Android     True         NaN
4      U0000005  2025-02-18  퍼포먼스광고  Android     True         NaN
...         ...         ...     ...      ...      ...         ...
12495  U0012496  2025-04-24     오가닉  Android    False         NaN
12496  U0012497  2025-01-28     오가닉  Android    False         NaN
12497  U0012498  2025-02-05     오가닉      iOS    False         NaN
12498  U0012499  2025-05-07     오가닉  Android     True         NaN
12499  U0012500  2025-05-22  퍼포먼스광고      iOS     True         NaN

[12500 rows x 6 columns]

          User_ID           Event_Time Event_Type  Session_ID   알림_유형
0        U0000001  2025-01-25 07:25:45        앱실행  2858201769     NaN
1        U0000001  2025-01-25 07:26:15     온보딩_완료  2858201769     NaN
2        U0000001  2025-01-25 07:26:55     챌린지_탐색  2858201769     NaN
3        U0000001  2025-01-25 07:27:55      챌린지참여  2858201769     NaN
4        U0000001  2025-01-25 20:30:00       알림수신         NaN     광고성
...           ...                  ...        ...         ...     ...
1757257  U0012500  2025-05-25 22:43:48        앱실행  c93feee9be     NaN
1757258  U0012500  2025-05-25 22:44:18       수면기록  c93feee9be     NaN
1757259  U0012500  2025-05-26 10:08:00       알림수신         NaN  챌린지_알림
1757260  U0012500  2025-05-26 10:41:35        앱실행  591113d3d1     NaN
1757261  U0012500  2025-05-26 10:57:49        앱실행  76055a2516     NaN

[1757262 rows x 5 columns]